/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @dfinity/caffeine-bindgen@0.1.0-beta.7.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  'fetchAptPrice' : ActorMethod<[], string>,
  'generateAndValidateMultiple' : ActorMethod<[bigint], undefined>,
  'generateMnemonic' : ActorMethod<[], Array<string>>,
  'getAvailableWords' : ActorMethod<[], Array<string>>,
  'getBip39Words' : ActorMethod<[], Array<string>>,
  'getCachedPrice' : ActorMethod<[], [] | [string]>,
  'getDevnetExplorerUrl' : ActorMethod<[string], string>,
  'getNetworkPreference' : ActorMethod<[string], [] | [string]>,
  'requestDevnetFaucet' : ActorMethod<[string], string>,
  'requestTestnetFaucet' : ActorMethod<[string], string>,
  'setBip39Words' : ActorMethod<[Array<string>], undefined>,
  'setNetworkPreference' : ActorMethod<[string, string], undefined>,
  'testGenerateMnemonic' : ActorMethod<[], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'validateMnemonic' : ActorMethod<[Array<string>], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];
